spring:
  main:
    banner-mode: 'console'
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop

cdn:
  endpoint: ${CDN_ENDPOINT}
  access-key-id: ${CDN_ACCESS_KEY}
  access-key-secret: ${CDN_ACCESS_SECRET}
  bucket:
    public: ${CDN_PUBLIC_BUCKET}
    private: ${CDN_PRIVATE_BUCKET}