spring:
  main:
    banner-mode: 'console'
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: admin-test
    password: ''
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
